//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notify.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public Cours()
        {
            this.Notes = new HashSet<Note>();
        }
    
        public int courseId { get; set; }
        public int portalCourseId { get; set; }
        public int userId { get; set; }
        public string courseName { get; set; }
        public Nullable<System.DateTime> dateAdded { get; set; }
    
        public virtual ICollection<Note> Notes { get; set; }
        public virtual User User { get; set; }
    }
}
