//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notify.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int noteId { get; set; }
        public int portalNoteId { get; set; }
        public int courseId { get; set; }
        public string noteName { get; set; }
        public string noteCustomPath { get; set; }
        public Nullable<System.DateTime> dateDownloaded { get; set; }
    
        public virtual Cours Cours { get; set; }
    }
}
