//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notify.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Courses = new HashSet<Cours>();
        }
    
        public int userId { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> profilePictureId { get; set; }
        public Nullable<System.DateTime> dateRegistered { get; set; }
    
        public virtual ICollection<Cours> Courses { get; set; }
    }
}
